name: stemplay_mathscollege
description: "Application éducative avec quiz et mini-jeux pour le collège."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # (Facultatif mais utile)
  google_fonts: ^6.2.1
  audioplayers: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1  # (pour la logique réactive si tu veux)
  lottie: ^3.1.0  # pour des animations modernes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/animations/
